[package]
name = "codescope-terminal"
version = "0.0.1"
edition = "2024"
publish = false
description = "Terminal emulator component for CodeScope-rs."

[dependencies]
alacritty_terminal = "0.25"
anyhow = "1"
codescope-core = { path = "../core" }
flume = { version = "0.11", default-features = false }
gpui = "0.2.2"
linkify = "0.10"
open = "5"
parking_lot = "0.12"
